/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cibertec.edu.views;

import com.cibertec.edu.model.Equipo;
import com.cibertec.edu.repository.EquipoRepository;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JTextField;
import javax.swing.JLabel;
import java.awt.Font;
import javax.swing.JButton;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 *
 * @author joanleonrs
 */
public class FormEquipos extends javax.swing.JFrame {
    
    private EquipoRepository equipoRepository = new EquipoRepository();
    private ResultSet resultSet;
    int ultimoIdxTablaSelected = -1;
    
    public void configurarFrame() {
        tableResultados.getTableHeader().setReorderingAllowed(false);
        tableResultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableResultadosMouseClicked(evt);
            }
        });
        btnAgregar.setVisible(false);
        btnNuevo.setVisible(true);
    }

    /**
     * Creates new form FormEquipos
     */
    public FormEquipos() {
        initComponents();
        configurarFrame();
        resetearFormulario();
        refrescarTablaEquipos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipalEquipo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtCategoria = new javax.swing.JTextField();
        cboEstado = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        btnBuscar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableResultados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));

        pnlPrincipalEquipo.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Mantenimiento de Equipos");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Modelo:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("C√≥digo de Equipo:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Categor√≠a:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Estado:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Marca:");

        txtModelo.setToolTipText("Ingrese el Modelo del Equipo");

        txtCodigo.setEditable(false);
        txtCodigo.setBackground(new java.awt.Color(204, 204, 255));

        cboEstado.setBackground(new java.awt.Color(51, 102, 255));
        cboEstado.setForeground(new java.awt.Color(255, 255, 255));
        cboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponible", "No Disponible" }));

        btnBuscar.setBackground(new java.awt.Color(0, 51, 153));
        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnAgregar.setBackground(new java.awt.Color(0, 51, 153));
        btnAgregar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(0, 51, 153));
        btnLimpiar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(0, 51, 153));
        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(0, 51, 153));
        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnNuevo.setBackground(new java.awt.Color(0, 51, 153));
        btnNuevo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

//        tableResultados.setModel(modeloInicial);
        jScrollPane2.setViewportView(tableResultados);
        
        txtCriterioBusqueda = new JTextField();
        txtCriterioBusqueda.setText("");
        
        lblCriterioBusqueda = new JLabel("Ingrese criterio de b\u00FAsqueda:");
        lblCriterioBusqueda.setFont(new Font("Tahoma", Font.PLAIN, 14));

        javax.swing.GroupLayout pnlPrincipalEquipoLayout = new javax.swing.GroupLayout(pnlPrincipalEquipo);
        pnlPrincipalEquipoLayout.setHorizontalGroup(
        	pnlPrincipalEquipoLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(pnlPrincipalEquipoLayout.createSequentialGroup()
        			.addGap(0)
        			.addGroup(pnlPrincipalEquipoLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(pnlPrincipalEquipoLayout.createSequentialGroup()
        					.addGroup(pnlPrincipalEquipoLayout.createParallelGroup(Alignment.LEADING)
        						.addGroup(pnlPrincipalEquipoLayout.createSequentialGroup()
        							.addGap(33)
        							.addGroup(pnlPrincipalEquipoLayout.createParallelGroup(Alignment.LEADING, false)
        								.addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        								.addGroup(pnlPrincipalEquipoLayout.createSequentialGroup()
        									.addGroup(pnlPrincipalEquipoLayout.createParallelGroup(Alignment.LEADING)
        										.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 137, GroupLayout.PREFERRED_SIZE)
        										.addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 137, GroupLayout.PREFERRED_SIZE)
        										.addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 137, GroupLayout.PREFERRED_SIZE)
        										.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 137, GroupLayout.PREFERRED_SIZE)
        										.addComponent(lblCriterioBusqueda))
        									.addGap(63)
        									.addGroup(pnlPrincipalEquipoLayout.createParallelGroup(Alignment.LEADING)
        										.addComponent(txtCriterioBusqueda, GroupLayout.PREFERRED_SIZE, 290, GroupLayout.PREFERRED_SIZE)
        										.addGroup(pnlPrincipalEquipoLayout.createParallelGroup(Alignment.LEADING, false)
        											.addComponent(txtCodigo)
        											.addComponent(cboEstado, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        											.addComponent(txtCategoria, GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        											.addComponent(txtMarca, GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        											.addComponent(txtModelo))))
        								.addComponent(jScrollPane2)))
        						.addGroup(pnlPrincipalEquipoLayout.createSequentialGroup()
        							.addGap(34)
        							.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 137, GroupLayout.PREFERRED_SIZE)))
        					.addGap(73)
        					.addGroup(pnlPrincipalEquipoLayout.createParallelGroup(Alignment.LEADING)
        						.addComponent(btnBuscar, GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
        						.addComponent(btnEliminar, GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
        						.addComponent(btnLimpiar, GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
        						.addGroup(pnlPrincipalEquipoLayout.createParallelGroup(Alignment.LEADING, false)
        							.addComponent(btnModificar, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(btnNuevo, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(btnAgregar, GroupLayout.PREFERRED_SIZE, 163, GroupLayout.PREFERRED_SIZE))))
        				.addGroup(pnlPrincipalEquipoLayout.createSequentialGroup()
        					.addGap(139)
        					.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 290, GroupLayout.PREFERRED_SIZE)))
        			.addGap(115))
        );
        pnlPrincipalEquipoLayout.setVerticalGroup(
        	pnlPrincipalEquipoLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(pnlPrincipalEquipoLayout.createSequentialGroup()
        			.addGroup(pnlPrincipalEquipoLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(pnlPrincipalEquipoLayout.createSequentialGroup()
        					.addGap(125)
        					.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE))
        				.addGroup(pnlPrincipalEquipoLayout.createSequentialGroup()
        					.addGap(43)
        					.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
        					.addGap(44)
        					.addGroup(pnlPrincipalEquipoLayout.createParallelGroup(Alignment.LEADING)
        						.addGroup(pnlPrincipalEquipoLayout.createSequentialGroup()
        							.addComponent(txtCodigo, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE)
        							.addGap(18)
        							.addGroup(pnlPrincipalEquipoLayout.createParallelGroup(Alignment.BASELINE)
        								.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE)
        								.addComponent(txtModelo, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE))
        							.addGap(18)
        							.addGroup(pnlPrincipalEquipoLayout.createParallelGroup(Alignment.BASELINE)
        								.addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE)
        								.addComponent(txtMarca, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE))
        							.addGap(21)
        							.addGroup(pnlPrincipalEquipoLayout.createParallelGroup(Alignment.BASELINE)
        								.addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE)
        								.addComponent(txtCategoria, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE))
        							.addGap(18)
        							.addGroup(pnlPrincipalEquipoLayout.createParallelGroup(Alignment.LEADING)
        								.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE)
        								.addComponent(cboEstado, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE))
        							.addGap(17)
        							.addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE))
        						.addGroup(pnlPrincipalEquipoLayout.createSequentialGroup()
        							.addGroup(pnlPrincipalEquipoLayout.createParallelGroup(Alignment.LEADING)
        								.addGroup(pnlPrincipalEquipoLayout.createSequentialGroup()
        									.addComponent(btnNuevo, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE)
        									.addPreferredGap(ComponentPlacement.RELATED)
        									.addComponent(btnAgregar, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE))
        								.addGroup(pnlPrincipalEquipoLayout.createSequentialGroup()
        									.addGap(90)
        									.addComponent(btnModificar, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE)))
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addComponent(btnLimpiar, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addComponent(btnEliminar, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE)))))
        			.addGap(3)
        			.addGroup(pnlPrincipalEquipoLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblCriterioBusqueda)
        				.addComponent(txtCriterioBusqueda, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnBuscar, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE))
        			.addGap(40)
        			.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 300, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(83, Short.MAX_VALUE))
        );
        pnlPrincipalEquipo.setLayout(pnlPrincipalEquipoLayout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(pnlPrincipalEquipo, GroupLayout.PREFERRED_SIZE, 839, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(pnlPrincipalEquipo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        
        boolean esValido = esFormularioValido();
        
        if (esValido == true) {
            int codigo = Integer.parseInt(txtCodigo.getText());
            String modelo = txtModelo.getText();
            String marca = txtMarca.getText();
            String categoria = txtCategoria.getText();
            boolean disponible = false;

            if(cboEstado.getSelectedIndex() == 0) {
                disponible = true;
            }

            Equipo equipoAIngresar = new Equipo(codigo, modelo, marca, categoria, disponible);
            agregarEquipo(equipoAIngresar);
            JOptionPane.showMessageDialog(null, "Equipo registrado \nexitosamente!");

            resetearFormulario();
            btnAgregar.setVisible(false);
            btnNuevo.setVisible(true);    
        }
        
    }//GEN-LAST:event_btnAgregarActionPerformed
    
    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        boolean esValido = esFormularioValido();
        
        if (esValido == true) {
            int codigo = Integer.parseInt(txtCodigo.getText());
            String modelo = txtModelo.getText();
            String marca = txtMarca.getText();
            String categoria = txtCategoria.getText();
            boolean disponible = false;

            if(cboEstado.getSelectedIndex() == 0){
                disponible = true;
            }

            Equipo equipoAModificar = new Equipo(codigo, modelo, marca, categoria, disponible);
            modificarEquipo(equipoAModificar);

            JOptionPane.showMessageDialog(null, "Equipo actualizado \nexitosamente!");

            resetearFormulario();
            btnAgregar.setVisible(false);
            btnNuevo.setVisible(true);    
        }
    }//GEN-LAST:event_btnModificarActionPerformed
    
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
    	if(txtCriterioBusqueda.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Por favor \ningrese un criterio \npara ejecutar \nla b˙squeda!");
            txtCriterioBusqueda.setText("");
            txtCriterioBusqueda.requestFocus();
            refrescarTablaEquipos();
        } else {
        	buscarEquipo(Integer.parseInt(txtCriterioBusqueda.getText()));
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        resetearFormulario();
        btnNuevo.setVisible(true);
        btnAgregar.setVisible(false);
        txtModelo.requestFocus();
        refrescarTablaEquipos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
    	
    	int opcionSeleccionada = JOptionPane.showConfirmDialog(null,"øDesea eliminar el equipo\n seleccionado?", "Eliminar equipo", JOptionPane.DEFAULT_OPTION);
        
        if(opcionSeleccionada == 0) {
            equipoRepository.deleteEquipo(txtCodigo.getText());
            ((DefaultTableModel)tableResultados.getModel()).removeRow(ultimoIdxTablaSelected);
            tableResultados.addNotify();
            resetearFormulario();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private DefaultTableModel obtenerModeloInicial() {
        Object[]cabeceras = {"CODIGO", "MODELO", "MARCA", "CATEGORIA", "ESTADO"};
        DefaultTableModel modeloInicial = new DefaultTableModel(cabeceras, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        return modeloInicial;
    }
    
    private void refrescarTablaEquipos() {
    	
    	DefaultTableModel modeloInicial = obtenerModeloInicial();

        resultSet = equipoRepository.getEquipos();
        try {
            while (resultSet.next()) {
                Equipo e = new Equipo();
                e.setCodigo(resultSet.getInt("codigo"));
                e.setCategoria(resultSet.getString("categoria"));
                e.setMarca(resultSet.getString("marca"));
                e.setModelo(resultSet.getString("modelo"));
                e.setDisponible(resultSet.getBoolean("disponible"));
                llenarCelda(e, modeloInicial);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "OcurriÛ un error en el sistema, por favor contacte al Administrador! Error: " + ex.getMessage());
        }
        tableResultados.setModel(modeloInicial);
    }
    
    private DefaultTableModel llenarCelda(Equipo e, DefaultTableModel modelo) {
        String[]celda = {
                String.valueOf(e.getCodigo()),
                e.getModelo(),
                e.getMarca(),
                e.getCategoria(), 
                ((e.isDisponible() == true ) ? "Disponible" : "No Disponible")
            };
        modelo.addRow(celda);
        return modelo;
    }
    
    private void agregarEquipo(Equipo e) {
    	equipoRepository.addEquipo(
    			e.getCodigo(), 
    			e.getModelo(), 
    			e.getMarca(), 
    			e.getCategoria(), 
    			e.isDisponible());
    	refrescarTablaEquipos();
    }
    
    private void modificarEquipo(Equipo e) {
    	equipoRepository.updateEquipo(
    			e.getCodigo(), 
    			e.getModelo(), 
    			e.getMarca(), 
    			e.getCategoria(), 
    			e.isDisponible());
    	refrescarTablaEquipos();
    }
    
    private void buscarEquipo(int codigoEquipo) {
    	
    	DefaultTableModel nuevoModelo = obtenerModeloInicial();
        resultSet = equipoRepository.buscarEquipos(codigoEquipo);
        try {
            while (resultSet.next()) {
                Equipo e = new Equipo();
                e.setCodigo(resultSet.getInt("codigo"));
                e.setCategoria(resultSet.getString("categoria"));
                e.setMarca(resultSet.getString("marca"));
                e.setModelo(resultSet.getString("modelo"));
                e.setDisponible(resultSet.getBoolean("disponible"));
                llenarCelda(e, nuevoModelo);
            }
//	        JOptionPane.showMessageDialog(null, "No se encontraron resultados \npara el criterio de \nb˙squeda ingresado.");
        	
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "OcurriÛ un error en el sistema, por favor contacte al Administrador! Error: " + ex.getMessage());
        }
        tableResultados.setModel(nuevoModelo);
    }
    
    private int obtenerUltimoCodigo() {
    	int codigoInicial = 1000;
    	ResultSet rs = equipoRepository.getUltimoCodigo();
    	try {
			if (rs.next() && rs.getInt(1) > 0) {
				codigoInicial = rs.getInt(1);
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
    	return codigoInicial;
    }
    
    private void resetearFormulario(){
    	btnEliminar.setEnabled(false);
    	btnModificar.setEnabled(false);
        txtCodigo.setText("");
        txtModelo.setText("");
        txtMarca.setText("");
        txtCategoria.setText("");
        cboEstado.setSelectedIndex(1);
        txtCodigo.requestFocus();
        txtCodigo.setText(obtenerNuevoCodigo());
        txtCriterioBusqueda.setText("");
    };
    
    private boolean esFormularioValido() {
        
        boolean esValido = false;
    
        if(txtModelo.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Por favor ingrese un modelo!");
            txtModelo.setText("");
            txtModelo.requestFocus();
        } else if (txtMarca.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese una marca!");
            txtMarca.setText("");
            txtMarca.requestFocus();
        } else if (txtCategoria.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese una categor√≠a!");
            txtCategoria.setText("");
            txtCategoria.requestFocus();
        } else {
            esValido = true;
        }
        
        return esValido;
    }
    
    private void tableResultadosMouseClicked(java.awt.event.MouseEvent evt) {
        try {
            int row = tableResultados.rowAtPoint(evt.getPoint());
            String codigo = tableResultados.getValueAt(row, 0).toString();
            String modelo = tableResultados.getValueAt(row, 1).toString();
            String marca = tableResultados.getValueAt(row, 2).toString();
            String categoria = tableResultados.getValueAt(row, 3).toString();
            String estado = tableResultados.getValueAt(row, 4).toString();
            txtCodigo.setText(String.valueOf(codigo));
            txtModelo.setText(String.valueOf(modelo));
            txtMarca.setText(String.valueOf(marca));
            txtCategoria.setText(String.valueOf(categoria));
            cboEstado.setSelectedIndex((estado == "Disponible" ? 0 : 1));
            ultimoIdxTablaSelected = row;
            btnAgregar.setVisible(false);
            btnNuevo.setVisible(true);
            btnModificar.setEnabled(true);
            btnEliminar.setEnabled(true);
        } catch (Exception e) {
            System.out.println("Mouse Click Error; " + e);
        }
    }
    
    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
    	btnModificar.setEnabled(false);
        btnAgregar.setVisible(true);
        btnNuevo.setVisible(false);
        txtModelo.requestFocus();
        txtCodigo.setText(obtenerNuevoCodigo());
    }//GEN-LAST:event_btnNuevoActionPerformed
    
    private String obtenerNuevoCodigo() {
    	int nuevoCodigo = obtenerUltimoCodigo(); 
    	return String.valueOf(nuevoCodigo += 1);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEquipos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cboEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pnlPrincipalEquipo;
    private javax.swing.JTable tableResultados;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private JTextField txtCriterioBusqueda;
    private JLabel lblCriterioBusqueda;
}
